"""
Soonic AI - Thin Vertical Slice Test Interface
FastAPI backend for chord detection from video/audio files
"""

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import subprocess
import os
import uuid
from pathlib import Path
from correction_layer_v1 import CorrectionLayerV1

app = FastAPI(title="Soonic AI Test API")

# Enable CORS for local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Directories
BASE_DIR = Path(__file__).parent.parent
UPLOAD_DIR = BASE_DIR / "uploads"
OUTPUT_DIR = BASE_DIR / "output"

# Ensure directories exist
UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)


@app.get("/")
async def root():
    return {"status": "Soonic AI Test API is running"}


@app.post("/analyze")
async def analyze_audio(file: UploadFile = File(...)):
    """
    Analyze uploaded audio/video file and return chord progression

    Expected processing time: 1-2 minutes
    """
    session_id = str(uuid.uuid4())[:8]

    try:
        # Step 1: Save uploaded file
        file_ext = os.path.splitext(file.filename)[1] or ".mp4"
        upload_path = UPLOAD_DIR / f"{session_id}{file_ext}"

        with open(upload_path, "wb") as f:
            content = await file.read()
            f.write(content)

        # Step 2: Extract audio using FFmpeg
        audio_path = OUTPUT_DIR / f"{session_id}.wav"

        ffmpeg_cmd = [
            "ffmpeg", "-i", str(upload_path),
            "-ar", "44100",
            "-ac", "1",
            "-y",
            str(audio_path)
        ]

        result = subprocess.run(
            ffmpeg_cmd,
            capture_output=True,
            text=True,
            timeout=120
        )

        if result.returncode != 0:
            raise HTTPException(
                status_code=500,
                detail=f"Audio extraction failed: {result.stderr}"
            )

        # Step 3: Run basic-pitch using Docker
        midi_output_dir = OUTPUT_DIR / session_id
        midi_output_dir.mkdir(exist_ok=True)

        docker_cmd = [
            "docker", "run", "--rm",
            "-v", f"{audio_path.parent}:/data",
            "-v", f"{midi_output_dir}:/output",
            "tensorflow/tensorflow:2.15.0",
            "bash", "-c",
            f"pip install -q basic-pitch && basic-pitch /output /data/{audio_path.name}"
        ]

        result = subprocess.run(
            docker_cmd,
            capture_output=True,
            text=True,
            timeout=300
        )

        if result.returncode != 0:
            raise HTTPException(
                status_code=500,
                detail=f"MIDI transcription failed: {result.stderr}"
            )

        # Find the generated MIDI file
        midi_files = list(midi_output_dir.glob("*.mid"))
        if not midi_files:
            raise HTTPException(
                status_code=500,
                detail="No MIDI file generated by basic-pitch"
            )

        midi_path = midi_files[0]

        # Step 4: Run correction layer
        corrector = CorrectionLayerV1(str(midi_path))
        result = corrector.process(
            window_size=0.5,
            min_chord_duration=0.5
        )

        # Step 5: Prepare response
        key_name, key_mode = corrector.detected_key, "major" if corrector.key_scale == [0, 2, 4, 5, 7, 9, 11] else "minor"

        NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

        response_data = {
            "session_id": session_id,
            "detected_key": f"{NOTE_NAMES[corrector.detected_key]} {key_mode}",
            "total_chords": len(result['chords']),
            "hand_separation": {
                "left_hand_notes": result['stats']['left_hand_notes'],
                "right_hand_notes": result['stats']['right_hand_notes'],
                "total_notes": result['stats']['total_notes']
            },
            "chords": [
                {
                    "time": chord_data['time'],
                    "chord": chord_data['chord'],
                    "confidence": round(chord_data['confidence'], 2),
                    "notes": chord_data['notes'],
                    "note_names": [NOTE_NAMES[pc] for pc in chord_data['notes']],
                    "hand": "left"
                }
                for chord_data in result['chords']
            ],
            "melody": [
                {
                    "time": melody_data['time'],
                    "note_names": melody_data['note_names'],
                    "hand": "right"
                }
                for melody_data in result['melody']
            ]
        }

        # Cleanup uploaded file
        upload_path.unlink(missing_ok=True)

        return JSONResponse(content=response_data)

    except subprocess.TimeoutExpired:
        raise HTTPException(
            status_code=504,
            detail="Processing timeout - file may be too long (max ~5 minutes)"
        )

    except Exception as e:
        # Cleanup on error
        if 'upload_path' in locals():
            upload_path.unlink(missing_ok=True)

        raise HTTPException(
            status_code=500,
            detail=f"Processing error: {str(e)}"
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
